login_key_1: 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
login_key_2: ABC123_FAKE_KEY_1111111111111111111111111
team_name: x-dong-ludwig-maximilian-university-of-munich
project_name: mfcvae-reproduction
